spring:
  cloud:
    function:
      definition: semanticSearch
  main:
    web-application-type: none
    lazy-initialization: true
  jmx:
    enabled: false

elasticsearch:
  endpoint: ${ELASTICSEARCH_ENDPOINT:https://ecommerce-project-a814cd.es.us-east-1.aws.elastic.cloud:443}
  apikey: ${ELASTICSEARCH_APIKEY:alBSNG41a0JUamwwcHZqNnoxaUs6Q2I0Ym5iNE14TkRvNEtDUXcyZF83Zw==}
  index: ${ELASTICSEARCH_INDEX:ecommerce-products}

logging:
  level:
    com.ecommerce.search: INFO
    org.springframework.cloud.function: DEBUG
    root: WARN