spring:
  cloud:
    function:
      definition: semanticSearch
  main:
    web-application-type: none
    lazy-initialization: true
  jmx:
    enabled: false

elasticsearch:
  endpoint: ${ELASTICSEARCH_ENDPOINT:https://host.aws.elastic.cloud:443}
  apikey: ${ELASTICSEARCH_APIKEY:apikewrwenbsdfshdfhsdfg==}
  index: ${ELASTICSEARCH_INDEX:ecommerce-products}

logging:
  level:
    com.ecommerce.search: INFO
    org.springframework.cloud.function: DEBUG
    root: WARN