spring:
  cloud:
    function:
      definition: semanticSearch

vector:
  db:
    endpoint: ${VECTOR_DB_ENDPOINT:https://your-opensearch-domain.region.es.amazonaws.com}
    index: ${VECTOR_DB_INDEX:products}

logging:
  level:
    com.ecommerce.search: INFO
    org.springframework.cloud.function: DEBUG